# Generated by Django 5.0.7 on 2024-08-05 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0011_comprehensivetest_add_by'),
        ('finance', '0002_invoce_invoiceitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoce',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinic.order'),
        ),
    ]
