# Generated by Django 5.0.7 on 2024-08-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_invoce_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoce',
            name='total_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
