# Generated by Django 5.0.7 on 2024-08-23 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_customeinvoiceitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoce',
            name='Custome_adjustment',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='invoce',
            name='Custome_discount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='invoce',
            name='Custome_total_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
