# Generated by Django 5.0.7 on 2024-07-25 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0001_initial'),
        ('Home', '0002_patient'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('patient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('doctor', models.CharField(default='Self', max_length=100)),
                ('hospital', models.CharField(default=' ', max_length=100)),
                ('order_number', models.CharField(editable=False, max_length=10, unique=True)),
                ('order_status', models.BooleanField(default=False)),
                ('approvel_status', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Home.patient')),
            ],
        ),
    ]
