# Generated by Django 5.0.7 on 2024-07-26 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0003_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sample',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
