# Generated by Django 5.0.7 on 2024-08-01 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0007_alter_testresult_result_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
