# Generated by Django 5.0.7 on 2024-08-02 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0009_order_test_name_comprehensivetest'),
    ]

    operations = [
        migrations.AddField(
            model_name='testtype',
            name='specimen',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
