# Generated by Django 5.0.7 on 2024-08-18 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0011_comprehensivetest_add_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='comprehensive_test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinic.comprehensivetest'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='is_comprehensive',
            field=models.BooleanField(default=False),
        ),
    ]
