# Generated by Django 5.0.7 on 2024-08-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0012_testresult_comprehensive_test_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sample_collected_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
