# Generated by Django 5.0.7 on 2024-08-26 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0014_testcategory_comprehensivetest_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testcategory',
            name='tests',
        ),
        migrations.AddField(
            model_name='testtype',
            name='test_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clinic.testcategory'),
        ),
    ]
