# Generated by Django 5.0.7 on 2024-08-26 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0015_remove_testcategory_tests_testtype_test_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='testtype',
            name='test_category',
        ),
        migrations.AddField(
            model_name='testcategory',
            name='tests',
            field=models.ManyToManyField(to='Clinic.testtype'),
        ),
    ]
