# Generated by Django 5.0.7 on 2024-08-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinic', '0017_remove_testcategory_tests_testtype_test_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testtype',
            name='normal_range',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='testtype',
            name='unit',
            field=models.CharField(blank=True, default=' ', max_length=50, null=True),
        ),
    ]
