# Generated by Django 5.0.7 on 2024-07-31 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_alter_patient_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lab_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('contect_number', models.CharField(max_length=100)),
                ('logo_of_lab', models.FileField(upload_to='lab_logo')),
            ],
        ),
    ]
