# Generated by Django 5.0.7 on 2024-07-31 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_labdetails'),
    ]

    operations = [
        migrations.RenameField(
            model_name='labdetails',
            old_name='contect_number',
            new_name='contact_number',
        ),
    ]
