# Generated by Django 5.0.7 on 2024-07-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0008_labdetails_country_labdetails_postel_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdetails',
            name='state',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
