# Generated by Django 5.0.7 on 2024-08-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_labdetails_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='labdetails',
            name='letter_head',
            field=models.FileField(blank=True, null=True, upload_to='letter_head_top'),
        ),
        migrations.AddField(
            model_name='labdetails',
            name='letter_head_down',
            field=models.FileField(blank=True, null=True, upload_to='letter_head_down'),
        ),
    ]
